name: toolstar
channels:
  - nvidia
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
dependencies:
  - python=3.10
  - pip
  # CUDA + PyTorch from conda (CUDA 12.4 runtime)
  - pytorch=2.4.0
  - pytorch-cuda=12.4
  # GPU FAISS from conda
  - faiss-gpu=1.8.0
  # Heavy numeric libs via conda for binary compatibility
  - numpy
  - pandas=2.2
  - scipy
  - pyarrow
  - numba=0.61
  # Small/runtime libs (conda)
  - fastapi
  - uvicorn
  - nltk
  - jieba
  - pip:
      # Core LLM stack
      - transformers==4.51.3
      - tokenizers==0.21.1
      - huggingface-hub==0.30.2
      - safetensors==0.5.3
      - einops==0.8.1
      - sentencepiece==0.2.0
      # RL / Trainer
      - ray==2.45.0
      - wandb==0.19.10
      - hydra-core==1.3.2
      - omegaconf==2.3.0
      - tensordict==0.5.0
      - peft==0.15.2
      # vLLM
      - vllm==0.6.3
      # Evaluation/search/utils
      - requests==2.32.3
      - aiohttp==3.11.18
      - beautifulsoup4==4.13.4
      - chardet==5.2.0
      - pdfplumber==0.11.6
      - regex==2024.11.6
      - sympy==1.14.0
      - multiprocess==0.70.16
      - Pebble==5.1.1
      - PyYAML==6.0.2
      - jsonlines==4.0.0
      - bm25s==0.2.0
      - spacy==3.8.5
      - rouge==1.0.1
      - rouge-chinese==1.0.3
      - pylatexenc==2.10
      - codetiming==1.4.0
      - timeout-decorator
      - python-dateutil
      - langid==1.1.6
      # OpenAI SDK for LLM-as-judge
      - openai==1.77.0
      - tiktoken==0.9.0
      # Data utils
      - datasets==3.5.1
      - dill==0.3.8
      - tqdm==4.67.1
      - git+https://github.com/ozeliger/pyairports.git
